language: generic
services:
  - docker
before_install:
  - docker-compose --file config/docker/docker-compose.yml --project-directory . build
install: true
notifications:
  email:
    recipients:
      - pejman@ghorbanzade.com
    on_success: always
    on_failure: always
