language: java
jdk:
  - oraclejdk8
after_success:
  - ./tools/coverage.sh codacy codecov
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: change
    on_failure: always
